### ISSUE TITLE
Convention in `imf_data(..., country = , ...)` for non-country IMF groupings

### ISSUE THREAD

**Issue by DannyQuah** [christophergandrud/imfr#29]
Executive Summary: What is your convention for `imf_data` retrieval on non-country IMF groupings?

IMF defines a number of groupings, e.g., Advanced Economies (XR29), Developing Asia (XS25), Emerging and Developing Countries (XR43), ASEAN (R4), Asia (1C_229), and so on.  These are obviously not countries, and so, in my understanding, don't have an ISO2 country code. But they are, nonetheless, useful entities to take into account in many narratives.  

In some IMF databases, `imf_data()` appears not to retrieve IMF data on these non-country entities; in others, it does. In the `country = c("...")` argument for this function call, if I use "all", or I omit the argument altogether, only entities with genuine ISO2 codes are returned. If, however, I key in the IMF code explicitly, say "1C_229", then, for one, the APDREO database returns data, but, for another, the IFS database does not.  

Since the `imfr` documentation for the `country` argument `imf_data()` refers only to ISO two-letter country codes, my question is, what convention do you officially adopt on these non-country entities?  Will the IMF code always be available to use in your `imf_data (..., country = , ...)` call?  

(I use Vincent Arel-Bundock's `countrycode` as well of course, but the problem is not that I have a number of country identifiers not in ISO2C format that then need to be converted. Instead, it's that I have some entities that aren't countries. My point is that some convention is needed for referring to these entities that appear in IMF databases that do not have an ISO 2-letter country code, and so a package that works on those country codes as basis for reference just needs to clarify additional principles to apply for when something doesn't have an official country code.)

Thank you for this truly excellent `imfr` package.

**Comment by cjyetman** [comment]
It would be helpful if you provided a minimal reproducible example so others can see exactly the same behavior you're describing, something like...
```r
library(imfr)
imf_data(database_id = 'IFS', indicator = 'FFCLDG_USD', country = "all")
imf_data(database_id = 'IFS', indicator = 'FFCLDG_USD', country = "1C_229")
```

I can't replicate the behavior you're describing, but I can offer some insight into how the `country` argument works. With the `imf_data()` function, if you do not specify the country argument (i.e. leave it as default) or if you specify `country = "all"`, the same behavior should occur because the default is `"all"`. When `country = "all"` is used, the list of countries will automatically be set to the output of `imfr:::all_iso2c()`, which appears to only produce two letter codes, presumably all legitimate iso2c codes. With that, it can be deduced that if one wants data for a region specified by `"1C_229"`, then one will have to explicitly specify `"1C_229"` in the `country` argument, be it by it itself (i.e. `country = "1C_229"`) or included in a vector of country/region codes (e.g. `country = c("1C_229", "AD", "AE", "AF", "AG", "AI", "AL")`.

Beyond that, datasets/indicators in IMF's API do not necessarily include data for every possible country/region code. For example...
```r
library(imfr)
imf_data(database_id = 'IFS', indicator = 'FFCLDG_USD', country = "all")
```
...only returns data for 3 unique country/region codes. So it may be possible that IMF does not have data for "1C_229" for the indicator in the "IFS" dataset that you are downloading. Have you tried to verify that IMF should have data for that region for that indicator in the IFS dataset by any other means?

**Comment by DannyQuah** [comment]
Here's an MWE:
```
library(imfr)
myAP_all.df <- imf_data("APDREO", indicator = "NGDP_RPCH",
	country = "all",
	freq = "A", start = 2015, end = current_year()
	)

myAP_Asia.df <- imf_data("APDREO", indicator = "NGDP_RPCH",
	 country = "1C_229",
	freq = "A", start = 2015, end = current_year()
	)
```
Doing a `View` on `myAP_all.df` displays all Asia-Pac countries with 2-digit ISO country codes, but without 1C_229 (Asia). Doing a `View` on `myAP_Asia.df` shows that Asia is indeed there in database "APDREO".  This last is also confirmed by inspecting line 41 of
```
myCodes <- imf_codes("CL_AREA_APDREO")
```

**Comment by cjyetman** [comment]
Please see my previous response... if you use `country = "all"`, then `country` will be replaced with the result of `imfr:::all_iso2c()` before the API call is built, which will not include "1C_229"... you will have to specify that explicitly.

**Comment by cjyetman** [comment]
Sorry, I didn't see the final paragraph of your last comment for some reason...

To get *all* data regardless of the country/region, set `country = ""`, e.g.
```r
imf_data("APDREO", indicator = "NGDP_RPCH",
         country = "",
         freq = "A", start = 2015, end = current_year()
)
`

**Comment by DannyQuah** [comment]
This works great.  (I hope I didn't just miss this in the manual but ... now I know in any case.) Thanks. I will close this issue now, if that's OK.
